jobs:
  build:
    permissions:
      contents: write
    # ...
    steps:
      # ...
      - uses: Kira-NT/mc-publish@v3
        with:
          # If your build toolchain doesn't place the resulting artifacts directly in build/libs/,
          # you will need to manually specify what you want to upload:
          # files: build/libs/fabric/!(*-@(dev|sources|javadoc)).jar

          # Only include this section if you wish to publish your assets to Modrinth.
          modrinth-id: AANobbMI
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish your assets to CurseForge.
          curseforge-id: 394468
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Only include this section if you wish to publish your assets to GitHub.
          github-token: ${{ secrets.GITHUB_TOKEN }}